import uuid
from dotenv import load_dotenv

# Initialize environment keys
load_dotenv()

from src.graph import build_graph
from src.memory import init_memory_db, save_message_to_db, load_conversation_history

def start_chat_session():
    # Setup infrastructure tables
    init_memory_db()
    
    print("=====================================================")
    print("🤖 Welcome to the Multi-Tool Agentic AI Workspace")
    print("=====================================================\n")
    
    # Prompt user for persistent tracking code
    session_input = input("Enter an existing Conversation ID to resume or press [Enter] for new session: ").strip()
    if session_input:
        conversation_id = session_input
        print(f"🔄 Resuming conversation session: {conversation_id}")
    else:
        conversation_id = str(uuid.uuid4())[:8]
        print(f"🆕 Created a new conversation session ID: {conversation_id}")
    
    # Compile the state graph architecture
    graph = build_graph()
    
    print("\nSystem online. Type 'exit' or 'quit' to terminate session.\n")
    
    while True:
        try:
            user_text = input("👤 You: ").strip()
            if not user_text:
                continue
            if user_text.lower() in ["exit", "quit"]:
                print("Goodbye!")
                break
            
            # 1. Store input message in database
            save_message_to_db(conversation_id, "user", user_text)
            
            # 2 & 3. Retrieve conversation history & package state context
            # Default N=6 messages (3 full turns) as per requirements
            history = load_conversation_history(conversation_id, n_turns=6)
            
            # 4. Invoke graph
            state = {"messages": history}
            response_state = graph.invoke(state)
            
            # Pull out the last message generated by an agent node
            agent_response = response_state["messages"][-1].content
            
            # Fix: LangChain/Gemini sometimes returns content as a list of blocks. 
            # Extract the plain string before saving to SQLite.
            if isinstance(agent_response, list):
                if len(agent_response) > 0 and isinstance(agent_response[0], dict) and "text" in agent_response[0]:
                    agent_response = agent_response[0]["text"]
                else:
                    agent_response = str(agent_response)
            else:
                agent_response = str(agent_response)
            
            # 5. Store response back to persistence layer
            save_message_to_db(conversation_id, "assistant", agent_response)
            
            # 6. Output to display console
            print(f"🤖 Assistant: {agent_response}\n")
            
        except KeyboardInterrupt:
            print("\nGoodbye!")
            break
        except Exception as e:
            print(f"An unexpected system error occurred: {str(e)}\n")

if __name__ == "__main__":
    start_chat_session()